/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ghost Protocol
 */
public class admindetail extends javax.swing.JFrame {

    /**
     * Creates new form admindetail
     */
    public admindetail() {
        initComponents();
        adm();
    }
    public void adm()
    {
        DefaultTableModel dm=new DefaultTableModel();
        List<adminbin> a=database.getAlladmin();
        dm.addColumn("Admin ID");
        dm.addColumn("First Name");
        dm.addColumn("Last Name");
        dm.addColumn("Gender");
        dm.addColumn("Date of Birth");
        dm.addColumn("Contact No");
        dm.addColumn("Email ID");
        dm.addColumn("City");
        
        
        for(adminbin em:a)
        {
        
            Object o[]=new Object[8];
            
            o[0]=em.getAdminid();
            o[1]=em.getName();
            o[2]=em.getLname();
            o[3]=em.getGender();
            o[4]=em.getDob();
            o[5]=em.getContact();
            o[6]=em.getEmailid();
            o[7]=em.getCity();
            
            dm.addRow(o);
        }
        Table.setModel(dm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        back = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        Field = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Table.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Admin ID", "First Name", "Last Name", "Gender", "Date of Birth", "Contact No", "Email ID", "City"
            }
        ));
        jScrollPane2.setViewportView(Table);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(240, 180, 910, 350);

        back.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(630, 600, 80, 25);

        refresh.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh);
        refresh.setBounds(740, 600, 90, 25);

        Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Field);
        Field.setBounds(10, 100, 190, 30);

        search.setBackground(new java.awt.Color(255, 153, 0));
        search.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        search.setText("Search By Name");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(210, 100, 200, 30);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin's Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 100, 230, 40);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("HOTEL CRECENT INTERNATIONAL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 20, 630, 50);

        delete.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(520, 600, 80, 25);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-100, -120, 3130, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        admininfo ai=new admininfo();
        ai.setBounds(0, 0, 1500, 800);
        ai.setVisible(true);
        this.hide();
    }//GEN-LAST:event_backActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        adm();
    }//GEN-LAST:event_refreshActionPerformed

    private void FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldActionPerformed
        adminbin a=new adminbin();
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        a.setName(Field.getText());
        DefaultTableModel dm=new DefaultTableModel();
        List<adminbin> c=database.getAlladminByName(a);
        dm.addColumn("Admin ID");
        dm.addColumn("First Name");
        dm.addColumn("Last Name");
        dm.addColumn("Gender");
        dm.addColumn("Date of Birth");
        dm.addColumn("Contact No");
        dm.addColumn("Email ID");
        dm.addColumn("City");

        for(adminbin em:c)
        {

            Object o[]=new Object[8];

            o[0]=em.getAdminid();
            o[1]=em.getName();
            o[2]=em.getLname();
            o[3]=em.getGender();
            o[4]=em.getDob();
            o[5]=em.getContact();
            o[6]=em.getEmailid();
            o[7]=em.getCity();

            dm.addRow(o);

        }
        Table.setModel(dm);
    }//GEN-LAST:event_searchActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
                a.setName(Field.getText());
                database.deleteAdmin(a);
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Field;
    private javax.swing.JTable Table;
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refresh;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
