/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ghost Protocol
 */
public class customerdetail2 extends javax.swing.JFrame {

    /**
     * Creates new form customerdetail2
     */
    public customerdetail2() {
        initComponents();
        cust();
    }
     public void cust()
        {
        DefaultTableModel dm=new DefaultTableModel();
        List<roombin> c=database.getAllRoomAndCust();
        dm.addColumn("customerid");
        dm.addColumn("customername");
        dm.addColumn("totalroom");
        dm.addColumn("roomno1");
        dm.addColumn("roomtype1");
        dm.addColumn("roomno2");
        dm.addColumn("roomtype2");
        dm.addColumn("checkin");
        dm.addColumn("checkout");
        dm.addColumn("amount");
        dm.addColumn("paymentoption");
        
        
        
        
        for(roombin rb:c)
        {
        
            Object o[]=new Object[11];
            
            o[0]=rb.getCustomerid();
            o[1]=rb.getCustomername();
            o[2]=rb.getTotalroom();
            o[3]=rb.getRoomno1();
            o[4]=rb.getRoomtype1();
            o[5]=rb.getRoomno2();
            o[6]=rb.getRoomtype2();
            o[7]=rb.getCheckin();
            o[8]=rb.getCheckout();
            o[9]=rb.getAmount();
            o[10]=rb.getPaymentoption();
            
            dm.addRow(o);
        }
        Table.setModel(dm);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        text = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("HAWK STUDY ILLINOIS TECH");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 20, 630, 50);

        text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textActionPerformed(evt);
            }
        });
        getContentPane().add(text);
        text.setBounds(10, 100, 190, 30);

        search.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(210, 100, 30, 30);

        Table.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Customer Name", "Total Rooms", "Roomno 1", "Roomtype 1", "Roomno2", "Roomtype 2", "Checkin", "Checkout", "Amount", "Payment Option"
            }
        ));
        jScrollPane2.setViewportView(Table);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(190, 200, 1000, 350);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        jLabel1.setText("Customers Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 100, 270, 40);

        delete.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(520, 600, 80, 25);

        refresh.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        refresh.setText(" Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh);
        refresh.setBounds(740, 600, 87, 25);

        back.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(640, 600, 65, 25);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-100, -120, 3130, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textActionPerformed
roombin r= new roombin();
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        r.setCustomername(text.getText());
        DefaultTableModel dm =new DefaultTableModel();
        List<roombin> rr=database.getAllRoomAndCustByName(r);
        dm.addColumn("customerid");
        dm.addColumn("customername");
        dm.addColumn("totalroom");
        dm.addColumn("roomno1");
        dm.addColumn("roomtype1");
        dm.addColumn("roomno2");
        dm.addColumn("roomtype2");
        dm.addColumn("checkin");
        dm.addColumn("checkout");
        dm.addColumn("amount");
        dm.addColumn("paymentoption");

        for(roombin rb:rr)
        {

            Object o[]=new Object[11];

            o[0]=rb.getCustomerid();
            o[1]=rb.getCustomername();
            o[2]=rb.getTotalroom();
            o[3]=rb.getRoomno1();
            o[4]=rb.getRoomtype1();
            o[5]=rb.getRoomno2();
            o[6]=rb.getRoomtype2();
            o[7]=rb.getCheckin();
            o[8]=rb.getCheckout();
            o[9]=rb.getAmount();
            o[10]=rb.getPaymentoption();

            dm.addRow(o);
        }
        Table.setModel(dm);

        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        r.setCustomername(text.getText());
        database.deleteCustAndRoom(r);
    }//GEN-LAST:event_deleteActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        cust();
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        customerinfo2 c=new customerinfo2();
        c.setBounds(0, 0, 1500, 800);
        c.setVisible(true);
        this.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerdetail2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerdetail2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerdetail2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerdetail2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerdetail2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refresh;
    private javax.swing.JButton search;
    private javax.swing.JTextField text;
    // End of variables declaration//GEN-END:variables
}
