/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ghost Protocol
 */
public class paymentpage extends javax.swing.JFrame {

    /**
     * Creates new form paymentpage
     */
    public paymentpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        paymentoption = new javax.swing.JComboBox();
        date = new javax.swing.JTextField();
        checkout = new javax.swing.JTextField();
        checkin = new javax.swing.JTextField();
        customerid = new javax.swing.JTextField();
        customername = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalamount = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        CObutton = new javax.swing.JButton();
        Dbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payment Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 90, 310, 38);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setText("Customer ID:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(460, 190, 84, 30);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setText("Customer Name:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(460, 240, 107, 30);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setText("CheckIn:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(460, 290, 56, 30);

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel11.setText("CheckOut:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(460, 340, 68, 30);

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel12.setText("Date:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(460, 390, 32, 30);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel13.setText("Payment Option:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(460, 490, 109, 30);

        paymentoption.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        paymentoption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Cash", "Credit Card", "Debit Card", "Others" }));
        paymentoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentoptionActionPerformed(evt);
            }
        });
        getContentPane().add(paymentoption);
        paymentoption.setBounds(680, 490, 200, 30);
        getContentPane().add(date);
        date.setBounds(680, 390, 150, 30);

        checkout.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                checkoutFocusLost(evt);
            }
        });
        getContentPane().add(checkout);
        checkout.setBounds(680, 340, 150, 30);
        getContentPane().add(checkin);
        checkin.setBounds(680, 290, 200, 30);

        customerid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customeridKeyReleased(evt);
            }
        });
        getContentPane().add(customerid);
        customerid.setBounds(680, 190, 200, 30);
        getContentPane().add(customername);
        customername.setBounds(680, 240, 200, 30);

        print.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(750, 580, 80, 27);

        Save.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save);
        Save.setBounds(525, 580, 80, 27);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("HAWK STUDY ILLINOIS TECH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 20, 630, 50);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("Total Amount:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 440, 110, 30);

        totalamount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                totalamountFocusGained(evt);
            }
        });
        totalamount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                totalamountMouseReleased(evt);
            }
        });
        totalamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalamountKeyReleased(evt);
            }
        });
        getContentPane().add(totalamount);
        totalamount.setBounds(680, 440, 200, 30);

        back.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(640, 580, 80, 27);

        CObutton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CObuttonFocusLost(evt);
            }
        });
        CObutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CObuttonActionPerformed(evt);
            }
        });
        getContentPane().add(CObutton);
        CObutton.setBounds(840, 340, 40, 30);

        Dbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Dbutton);
        Dbutton.setBounds(840, 390, 40, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-100, -120, 3130, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paymentoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentoptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentoptionActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
           printpage pp=new printpage();
           pp.setBounds(0, 0, 1500, 800);
           pp.setVisible(true);
           pp.show();
           this.hide();
    }//GEN-LAST:event_printActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
     roompage r=new roompage();
     r.setBounds(0, 0, 1500, 800);
     r.setVisible(true);
     this.hide();
    }//GEN-LAST:event_backActionPerformed

    private void DbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DbuttonActionPerformed
       JFrame f=new JFrame();
        date.setText(new DatePicker(f).setPickedDate());
    }//GEN-LAST:event_DbuttonActionPerformed

    private void CObuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CObuttonActionPerformed
       JFrame f=new JFrame();
        checkout.setText(new DatePicker(f).setPickedDate());
    }//GEN-LAST:event_CObuttonActionPerformed
    roombin p=new roombin();
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
       p.customerid=Integer.parseInt(customerid.getText());
       p.customername=customername.getText();
       p.checkin=checkin.getText();
       p.checkout=checkout.getText();
       p.date=date.getText();
       p.paymentoption=paymentoption.getSelectedItem().toString();
       p.amount=Integer.parseInt(totalamount.getText());
       
       database.updateroomdetail(p);
       int cid=0;
       int cid1=0;
        int id= Integer.parseInt(customerid.getText());
        List<roombin >r=   database.getAllRoomByCustID(id);
        for(roombin rb:r){
        cid=rb.getRoomno1();
        cid1=rb.getRoomno2();
        }
       
       database.updateroomNAvailable(cid);
       database.updateroomNAvailable(cid1);

    }//GEN-LAST:event_SaveActionPerformed

    private void customeridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customeridKeyReleased
        p.customerid=Integer.parseInt(customerid.getText());
        List<roombin> rr=database.getAllRoomdetailByID(p);
        for(roombin rb:rr){
             
                   customername.setText(rb.getCustomername());
                   checkin.setText(rb.getCheckin());
                   totalamount.setText(rb.getAmount()+"");
        }

      
    }//GEN-LAST:event_customeridKeyReleased

    private void checkoutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_checkoutFocusLost

    }//GEN-LAST:event_checkoutFocusLost

    private void CObuttonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CObuttonFocusLost

  
    }//GEN-LAST:event_CObuttonFocusLost

    private void totalamountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalamountFocusGained

    }//GEN-LAST:event_totalamountFocusGained

    private void totalamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalamountKeyReleased

    }//GEN-LAST:event_totalamountKeyReleased

    private void totalamountMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalamountMouseReleased

    }//GEN-LAST:event_totalamountMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymentpage().setVisible(true);
            }
        });
    }
    
String fd,sd,am;
Date d,d1;
long diff;
int i,amt;
int ta=0;

    public void Cal() throws ParseException{
        
              fd=checkin.getText();
               sd=checkout.getText();
             
             DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
             d= df.parse(sd);
             d1= df.parse(fd);
            
              diff= Math.round((d.getTime() - d1.getTime()) / (double) 86400000);
             i=(int)diff;
             System.out.println(i);
             
              am=totalamount.getText();
              amt=Integer.parseInt(am);
              ta=amt*i;
             System.out.println(ta);
            totalamount.setText(ta+"");

            JOptionPane.showMessageDialog(this, "Wrong Format");
        
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CObutton;
    private javax.swing.JButton Dbutton;
    private javax.swing.JButton Save;
    private javax.swing.JButton back;
    private javax.swing.JTextField checkin;
    private javax.swing.JTextField checkout;
    private javax.swing.JTextField customerid;
    private javax.swing.JTextField customername;
    private javax.swing.JTextField date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox paymentoption;
    private javax.swing.JButton print;
    private javax.swing.JTextField totalamount;
    // End of variables declaration//GEN-END:variables
}
