/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Ghost Protocol
 */
public class roominsert2 extends javax.swing.JFrame {
    roombin r=new roombin();

    /**
     * Creates new form roominsert2
     */
    public roominsert2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        roomno = new javax.swing.JTextField();
        roomtype = new javax.swing.JTextField();
        roomprice = new javax.swing.JTextField();
        availability = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        back = new javax.swing.JButton();
        update = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("HAWK STUDY ILLINOIS TECH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 20, 630, 50);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        jLabel1.setText("Room Insert");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 100, 168, 50);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("Room No:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 210, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setText("Room Type:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 280, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setText("Room Price:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 350, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("Availability:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(500, 420, 90, 30);

        roomno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                roomnoKeyReleased(evt);
            }
        });
        getContentPane().add(roomno);
        roomno.setBounds(640, 210, 190, 30);
        getContentPane().add(roomtype);
        roomtype.setBounds(640, 280, 190, 30);
        getContentPane().add(roomprice);
        roomprice.setBounds(640, 350, 190, 30);
        getContentPane().add(availability);
        availability.setBounds(640, 420, 190, 30);

        insert.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        getContentPane().add(insert);
        insert.setBounds(500, 530, 90, 25);

        back.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(740, 530, 90, 25);

        update.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(620, 530, 90, 25);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(10, 630, 190, 30);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-100, -120, 3130, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomnoKeyReleased

    }//GEN-LAST:event_roomnoKeyReleased

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        r.roomno=Integer.parseInt(roomno.getText());
        r.roomtype=roomtype.getText();
        r.roomprice=Integer.parseInt(roomprice.getText());
        r.availability=availability.getText();
        database.createRoominsert(r);
        JOptionPane.showMessageDialog(this, "Rooms Insert Sucessfully", "INSERT", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_insertActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        roominfo2 r= new roominfo2();
        r.setBounds(0, 0, 1500, 800);
        r.setVisible(true);
        this.hide();
    }//GEN-LAST:event_backActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        r.setRoomno(Integer.parseInt(roomno.getText()));
        r.setRoomtype(roomtype.getText());
        r.setRoomprice(Integer.parseInt(roomprice.getText()));
        r.setAvailability(availability.getText());

        database.updateRoomInsert(r);

        JOptionPane.showMessageDialog(this, "Rooms Update Sucessfully", "UPDATE", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_updateActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        r.setRoomno(Integer.parseInt(search.getText()));
        List<roombin> rb=database.getAllRoominsertByRoomno(r);

        for(roombin rh:rb){

            roomno.setText(rh.getRoomno()+"");
            roomtype.setText(rh.getRoomtype());
            roomprice.setText(rh.getRoomprice()+"");
            availability.setText(rh.getAvailability());
        }
    }//GEN-LAST:event_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(roominsert2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(roominsert2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(roominsert2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(roominsert2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new roominsert2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availability;
    private javax.swing.JButton back;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField roomno;
    private javax.swing.JTextField roomprice;
    private javax.swing.JTextField roomtype;
    private javax.swing.JTextField search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
